# Site title
title: Inspiring Life Design

# Site description
description: Dream Big. Live joyfully. Design a life you love.

# Social Media accounts
social-media:
  youtube:   https://www.youtube.com/c/inspiringlifedesign
  instagram: https://www.instagram.com/inspiringlifedesign/
  facebook:  https://facebook.com/inspiringlifedesign/

# Contact email address
email: hello@inspiringlifedesign.com

# Google analytics 4 measurement ID
ga4-measurement-id: G-9ZQGS6X9B7

# Default post URLs
permalink: /posts/:title.html

# Collections
collections:
  tag_pages:
    output: true
    permalink: /tag/:title.html

# Home page pagination settings
paginate: 5
paginate_path: "/page/:num/"

# Files to exclude from build
exclude:
  - CNAME
  - docker-compose.yml

plugins: [jekyll-paginate]
