# Site title
title: Inspiring Life Design

# Site description
description: Life is for doing what you love. Designing a life of financial independence, free from working for anyone else, & inspiring others to do the same, is my passion

# Social Media accounts
social-media:
  youtube:   https://www.youtube.com/c/inspiringlifedesign
  instagram: https://www.instagram.com/inspiringlifedesign/
  twitter:   https://twitter.com/lifedesigntoday
  facebook:  https://facebook.com/inspiringlifedesign/

# Contact email address
email: hello@inspiringlifedesign.com

# Google analytics ID
google-analytics: UA-103634480-1

# Default post URLs
permalink: /posts/:title.html

# Collections
collections:
  tag_pages:
    output: true
    permalink: /tag/:title.html

# Home page pagination settings
paginate: 5
paginate_path: "/page/:num/"

# Files to exclude from build
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml

plugins: [jekyll-paginate]
